### ISSUE TITLE
Issues running pymeeus from a fresh install in a venv using pip install

### ISSUE THREAD

**Issue by benoitespinola** [architest/pymeeus#19]
Greetings,

I made a fresh install of pymeeus in a venv (using `pip install` in the venv after creating the venv). For this installation, I used Python 3.10.6

When I try to run the following script:

```
import pymeeus

epoch = pymeeus.Epoch(1992, 10, 13.0)
l, b, r = pymeeus.Earth.geometric_heliocentric_position(epoch, tofk5=False)

print(round(l.to_positive(), 6))
print(b.dms_str(n_dec=3))
print(round(r, 8))
```
You might recognize the code from an example for pymeeus.

I get the following error:
```
Traceback (most recent call last):
  File "/home/espinola/Code/test/test.py", line 3, in <module>
    epoch = pymeeus.Epoch(1992, 10, 13.0)
AttributeError: module 'pymeeus' has no attribute 'Epoch'
```
I got no errors or warnings when performing the pip install.

**Comment by benoitespinola** [comment]
I tried copying and pasting the relevant code from Epoch (and its dependencies from base and Angle )and I could create an Epoch.

The same issue happened with pymeeus.Earth:

```
Traceback (most recent call last):
  File "/home/espinola/Code/test/test.py", line 6, in <module>
    l, b, r = pymeeus.Earth.geometric_heliocentric_position(epoch, tofk5=False)
AttributeError: module 'pymeeus' has no attribute 'Earth'
```

**Comment by benoitespinola** [comment]
Dear Dagoberto,

Thank you for the very clear and quick response.

Importing the modules as you suggested works like a charm.

Your idea to add an appendix in the documentation clarifying the issue is good.

Best regards,

Benoit
